<!-- The main content of the about sub-page of the website -->
<main>
    <div class="container">
        <div class="about">
            <img src="assets/Premier_League_Logo.svg.png" style="border-radius: 16px; width: 30%;">
            <p>The Premier League is the highest level of the English football league system. Contested by 20 clubs, it operates on a system of promotion and relegation with the English Football League (EFL). Seasons typically run from August to May, with each team playing 38 matches against all other teams, both home and away.[1] Most games are played on Saturday and Sunday afternoons, with occasional weekday evening fixtures.[2]</p>
            <p>The competition was founded as the FA Premier League on 20 February 1992 following the decision of First Division (top-tier league from 1888 until 1992) clubs to break away from the English Football League. However, teams may still be relegated to and promoted from the EFL Championship. The Premier League takes advantage of a lucrative television rights sale to Sky:[3] from 2019 to 2020, accumulated television rights were worth around £3.1 billion a year, with Sky and BT Group securing the domestic rights to broadcast 128 and 32 games, respectively.[4][5] The Premier League is a corporation where chief executive Richard Masters is responsible for its management, with member clubs acting as shareholders.[6] Clubs were apportioned central payment revenues of £2.4 billion in 2016–17, with a further £343 million in solidarity payments to EFL clubs.[7]</p>
            <p>The Premier League is the most-watched sports league in the world, broadcast in 212 territories to 643 million homes, with a potential TV audience of 4.7 billion people.[8][9] For the 2018–19 season, the average Premier League match attendance was at 38,181,[10] second to the German Bundesliga's 43,500,[11] while aggregated attendance across all matches was the highest of any association football league at 14,508,981,[12] and most stadium occupancies are near capacity.[13] As of 2023, the Premier League is ranked first in the UEFA coefficient rankings based on performances in European competitions over the past five seasons, ahead of Spain's La Liga.[14] The English top-flight has produced the second-highest number of European Cup / UEFA Champions League titles, with a record six English clubs having won fifteen European championships in total.[15]</p>
            <span class="about-hidden">Dont forget that there are <?= getTeamCount($teams) ?> teams in Hans array! <a href="cityValues.php">Here</a> are some data from that array only for you! </span>
        </div>
    </div>
</main>